services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - app_network
  pg-vector:
    image: pgvector/pgvector:pg16
    container_name: pg_vector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    networks:
      - app_network
  redis:
    image: redis:7.4-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ~/.redis:/data
    networks:
      - app_network
  ai-backend:
    build:
      context: ./ai-assistant-backend
    image: ai-backend:latest
    pull_policy: never
    container_name: ai-backend
    ports:
      - "8765:8080"
    networks:
      - app_network
  ai-frontend:
    build:
      context: ./ai-assistant-frontend
    image: ai-frontend:latest
    pull_policy: never
    container_name: ai-frontend
    ports:
      - "8642:8501"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge