spring:
  application:
    name: AI-Assistant
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
    chat:
      client:
        enabled: false
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano
      embedding:
        options:
          model: text-embedding-3-small
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash-lite
    ollama:
      base-url: http://ollama:11434
      chat:
        options:
          model: gemma2:2b
  datasource:
    url: jdbc:postgresql://pg_vector:5432/vector_db
    username: user
    password: password
  data:
    redis:
      host: redis
      port: 6379
      password: password