spring:
  application:
    name: AI-Assistant
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: ${VECTOR_DIMENSIONS}
        initialize-schema: true
    chat:
      client:
        enabled: false
      memory:
        repository:
          redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: ${GOOGLE_CHAT_MODEL}
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}